name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      EC2_HOST: ${{ secrets.EC2_HOST }}
      EC2_USER: ubuntu
      EC2_KEY_PATH: /tmp/ec2_key.pem
      APP_DIRECTORY: /var/www/html/students

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js 20.17.1
      uses: actions/setup-node@v3
      with:
        node-version: '20.17'
    
    - name: Create SSH key file
      run: |
        echo "${{ secrets.EC2_KEY }}" > $EC2_KEY_PATH
        chmod 400 $EC2_KEY_PATH

    - name: Copy files to EC2
      run: |
        rsync -avz -e "ssh -i $EC2_KEY_PATH -o StrictHostKeyChecking=no" --exclude 'vendor/' --exclude 'tests/' --exclude 'node_modules/' --exclude '.git/' . $EC2_USER@$EC2_HOST:$APP_DIRECTORY
    
    - name: SSH into EC2 and run deployment scripts
      run: |
        ssh -i $EC2_KEY_PATH -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST << 'EOF'
        cd $APP_DIRECTORY
        npm run build
        EOF

    - name: Clean up
      run: rm -f $EC2_KEY_PATH
